apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    env: production
    owner: toba
    webserver: nginx
    country: EG


spec:
  containers:
  - name: nginx
    image: name:latest
    ports:
    - containerPort: 80
