apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: web
          image: bitnami/apache:latest
          ports:
            - containerPort: 80
