apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-deployment
  labels:
    name: helloserver
spec:
  replicas: 8  
  selector:
    matchLabels:
      app: helloserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: helloserver
    spec: 
      containers:
        - name: helloserver
          image: toba44/k8s-web-service
          ports: 
            - containerPort: 3000
